maintainer       "Atalanta Systems Ltd"
maintainer_email "support@atalanta-systems.com"
license          "Apache 2.0"
description      "Example cookbook metadata file"
long_description "Long version"
version          "2.2.11"
